// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  tutorialSidebar:  [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics',
      items: [
        'readme', // This is our main intro page in docs/
        {
          type: 'autogenerated',
          dirName: '.', // "." means the current docs folder (excluding subdirectories)
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1-robotic-nervous-system-ros2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-2-digital-twin-gazebo-unity',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-3-ai-robot-brain-nvidia-isaac',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-4-vision-language-action-vla',
        },
      ],
    },
  ],
};

module.exports = sidebars;


